GET http://localhost:1992/bananas?couleur=jaune

###
POST http://localhost:1992/instruments
Content-Type: application/json

{
    "name": "magic flute",
    "weight": 1.2,
    "color": "gold",
    "price": 999.99
}

###
GET http://localhost:1992/instruments

###
GET http://localhost:1992/instruments/1

###
PUT http://localhost:1992/instruments/2
Content-Type: application/json

{
    "name": "normal flute",
    "weight": 2.1,
    "color": "brown",
    "price": 9.99
}
 
###
DELETE  http://localhost:1992/instruments/3





###
GET  http://localhost:1992/bananas?couleur=jaune

###
GET  http://localhost:1992/bananas
###
GET  http://localhost:1992/bananas?couleur=purple



###
GET http://localhost:1992/users/

###
POST http://localhost:1992/users
Content-Type: application/json

{
    "username": "john_doe",
    "password": "mypassword123"
}

###
GET http://localhost:1992/users/1

###
PUT http://localhost:1992/users/1
Content-Type: application/json

{
    "username": "gandalf_theGrey",
    "password": "youshallnotpass"
}

###
DELETE http://localhost:1992/users/1

###
POST http://localhost:1992/login
Content-Type: application/json

{
    "username": "john_doe",
    "password": "mypassword123"
}

###
POST http://localhost:1992/instruments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTczODg0OTUxN30.Ogfg-wpgT3g34JNjzM3qh_5L1M-rtQm4-u_feqKhwTA

{
    "name": "protected flute",
    "weight": 2.2,
    "color": "silver",
    "price": 99.9
}

###
POST http://localhost:1992/reparations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTczODg0OTUxN30.Ogfg-wpgT3g34JNjzM3qh_5L1M-rtQm4-u_feqKhwTA
Content-Type: application/json

{
    "name": "terrible sound",
    "price": 55,
    "instrumentId": 5
}

###
DELETE http://localhost:1992/reparations/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTczODg0OTUxN30.Ogfg-wpgT3g34JNjzM3qh_5L1M-rtQm4-u_feqKhwTA

